server:
  port: 8002
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
myGateway:
  RoutePrefix: api
spring:
  profiles:
    active: dev
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  cloud:
    gateway:
      enabled: true
cryptographic:
  AESKey: hello
#  In product environment, private-keys must be replaced and kept private
chilunapispace:
  private-key: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDm7bifjQwBVAUrOrfxwuts9Evk7qUeWCTp8LA/Hr4BCAeQzuegdT1KNh5o2gLnicFUrhS7Jen6XPwm5Rg85WUSoxSv1ervQAbjbLxJg08m+K4upuqDoT7QZA4NcrvpLzKWnDMvO8wXyduhgayd8ue6yqAzWrDRICKM9M87mYfgDiwlQSluzRUymaCzlxLUynn8qiVS/Ze/2e0KW9l7woQpnvHWx5r9qH+EcujoX31xMf1Ln0ZS7dUTcDAa0UFBxjpJkmN90OnJaS9rmlkuMjS2pyvBnhTW/ZdPnbJV6lF64fDx61TJJZuiIlf/37qeku98fPf9it5Pzf48Zz41hpoJAgMBAAECggEAQ9s/oHaIPA2t1SWUbpB5sFLayEMNtuxssGdeyrVkXJY47ua1blN09o0Pg3zoVJQIgLMEeXerGLvhBibUZ/R6Li9IgWCo/7N/Mq29aBaTGB8Dw8ada59if0afUHlR2TPauCHe8nauQqE4je02RVVenWc0CtMP2OuJ64R2LouvPvksIopJuT8AaviICrJkQnN1ea6fWxZil0aYeL52hwZ0ltoIqkDNZpBoaI6m54fMy3Yu+2f1Hxpzxzj3WrJQJV92qnmA+54WnqDy0gTY7n+u7DxoDmsrInTTapQzZRLqveUQ9PWyQiVf9pSK4exd/oiqMzULD5YF3dgr6Uc7tNTSxwKBgQDpimgEbmT7+y1z71zVt5N4Zcwv6IuQnI+JZ1RZyCRd1/NDBEEwwJ4/dkWs7+fEqGnphSYa2s86+g3jSLfj89iKgY9B385b0Oz6LNja0DgpVL+vy3qKLXno6YdPKtFQjcBeP5B23GPE7v3lqbh55dgrFCP+uDGQJLPbmihwR58j6wKBgQD9IwIVx7GHnOfuRUgqDaUvE/AVeGg1T443UzPbD7+uWqzkc4X5aVR3432Kes0g3MnhF7Deie6PjGVzGpfT7TrcloL0q5M32jHq9hx0iCztLIonNgErqImvWbx4aGIgiL2zZf6zM5i6HNbOaiFTM27ssE1aA0W0ZbZ1Afu9IdCg2wKBgB9aA0jFAS2KtLlhotbWBCgfkl/EGihZvDM3+ezrn2YxvWh7w7ylvxjJ6eSjeDvAWCePRmRIh5VlSEQA2R7y91jwt6iiQPO2gnm7V4lYdpGl3O3epR6zqDAKWa3ZE6x6ux5r7hrmz0X6x37zX96Nao2t8H8bfxvYsYSDl3YrR0PtAoGBAIXwoSjPGhOMpXgA9rcxsyae4RkrNdCHgNOrVbPiuGTUG8lhixE2d3hcSdAdPC7YRIWy2GZYC3+vJPrrpkx/qPaROUenBWW3MVSG1vWeHE9+krc+rw3fxsKes8fuS4W1dNLY9BT0ByrrGYnsxCdW/qmEe9lWA+r5Krrsyrv/iXmjAoGBAJMyaza6SQPKmcCYq14hHAG8EBfO+xCc99uGIxhKof80Lw8OkpTOLlXwifAxSXLU8oi+QFwq7ksOxLMdZV9nT3oxgqOc4uTyOv5BVg02UzFZJkjX0a2BDiOS7wbtg+hMTpAAq3mBltUe+e/SOhY1h/1aNVbL00r7GywFbf8Be1k3